# project euler soru 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

f0, f1, total = 1, 1, 0
while f1 < 4000000:
    f0, f1 = f1, f0 + f1
    if f0 % 2 == 0:
        total += f0
print(total)
